### ISSUE TITLE
Authorization fails with new Twitch API rules

### ISSUE THREAD

**Issue by satanch** [Bioblaze/passport-twitch.js#11]
According to this: https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916
Now we have:

```
InternalOAuthError: failed to fetch user profile
```

Beacause of:
```
1|backend  | {
1|backend  |   statusCode: 401,
1|backend  |   data: '{"error":"Unauthorized","status":401,"message":"Client ID and OAuth token do not match"}'
1|backend  | }
```

Fix ASAP, please.

**Comment by Bioblaze** [comment]
what version are you using?

I recently updated it a week ago with those exacte changes i thought.

**Comment by satanch** [comment]
@Bioblaze You are totally right. Update is required.
