### ISSUE TITLE
Error 401 Twitch Api

### ISSUE THREAD

**Issue by markito12** [Bioblaze/passport-twitch.js#9]
**Describe the bug**
My app used to work fine but now i get this error
{
  statusCode: 401,
  data: '{"error":"Unauthorized","status":401,"message":"Client ID and OAuth token do not match"}'
}

**To Reproduce**
1. Initialize passport twitch

**Expected behavior**
To get all information on the callback

**Screenshots**
-
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version ..

**Smartphone (please complete the following information):**
-

**Comment by dedg3** [comment]
As an "hotfix" just use the following in your package.json until npm/yarn is fetching the correct version.

`"passport-twitch.js": "github:Bioblaze/passport-twitch.js",`

**Comment by Bioblaze** [comment]
i'm going to update npm here in a bit.

**Comment by markito12** [comment]
Ok thanks!

**Comment by markito12** [comment]
options.customHeaders['Authorization'] = "Bearer YourClientID"

as temporary fix it works

**Comment by Bioblaze** [comment]
thats very ood, i'll look at the code and test it out give me a bit.

**Comment by markito12** [comment]
No! Your package works fine, idk why npm installed the wrong version using
the github repo link

> thats very ood, i'll look at the code and test it out give me a bit.
>
>
